name: lavinmqperf benchmark
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  spec:
    name: Spec
    runs-on: ubuntu-latest
    container: 84codes/crystal:latest-ubuntu-20.04
    steps:
      - name: Print Crystal version
        run: crystal -v

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: 'pr'

      - name: Build lavinmq
        run: cd pr && make -j bin/lavinmq bin/lavinmqperf DOCS= CRYSTAL_FLAGS=-Dbake_static

      - name: Perf
        run: cd pr && chmod u+x extras/action_benchmark.sh && ./extras/action_benchmark.sh /tmp/pr.log

      - name: Checkout main
        uses: actions/checkout@v3
        with:
          path: 'main'
          ref: 'main'

      - name: Build lavinmq
        run: cd main && make -j bin/lavinmq bin/lavinmqperf DOCS= CRYSTAL_FLAGS=-Dbake_static

      - name: Perf
        run: cp pr/extras/action_benchmark.sh main/extras/action_benchmark.sh && cd main && ./extras/action_benchmark.sh /tmp/main.log

      - name: Compare
        run: |
          PR_LOG_CONTENTS=$(cat /tmp/pr.log)
          MAIN_LOG_CONTENTS=$(cat /tmp/main.log)
          PR_PUBLISH=$(tail -n 2 /tmp/pr.log | head -n 1)
          PR_CONSUME=$(tail -n 1 /tmp/pr.log)
          MAIN_PUBLISH=$(tail -n 2 /tmp/main.log | head -n 1)
          MAIN_CONSUME=$(tail -n 1 /tmp/main.log)
          echo "PR_PUBLISH='$PR_PUBLISH'" >> $GITHUB_ENV
          echo "PR_CONSUME='$PR_CONSUME'" >> $GITHUB_ENV
          echo "MAIN_PUBLISH='$MAIN_PUBLISH'" >> $GITHUB_ENV
          echo "MAIN_CONSUME='$MAIN_CONSUME'" >> $GITHUB_ENV

      - name: comment
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            **Main benchmark**
            ${{ env.MAIN_PUBLISH }}
            ${{ env.MAIN_CONSUME }}

            **PR benchmark**
            ${{ env.PR_PUBLISH }}
            ${{ env.PR_CONSUME }}

            _Keep in mind, these numbers are not representative of LavinMQ's peak performance.
            It is rather an indication of how the changes of this pull request affects the performance of the main branch._
