on:
  push:
    tags:
      - v*
  workflow_dispatch:

name: Create Release

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Release
        run: |
          VERSION="${{ github.ref_name }}"
          PRERELEASE_FLAG=""
          if [[ "$VERSION" =~ (alpha|beta|rc) ]]; then
            PRERELEASE_FLAG="--prerelease"
          fi
          gh release create "${{ github.ref }}" --notes "$(./.github/generate-release-notes)" $PRERELEASE_FLAG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  dispatch: # initiate dispatch, send trigger to lavinmq-website
    name: Dispatch
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Dispatch to workflow
        run: |
          curl -X POST https://api.github.com/repos/84codes/lavinmq-website/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.REPO_ACCESS_84C }} \
          --data '{"event_type": "new_release", "client_payload": { "version": "'"${{ github.ref_name }}"'" }}'
