name: Rerun Failed Workflow
on:
  workflow_dispatch:
    inputs:
      run_id:
        required: true
# TODO: Remove when crystal releases fix for bug affecting our debian workflow
jobs:
  rerun_on_failure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Rerun workflow
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh run rerun ${{ inputs.run_id }} --failed
